name: CI Test Code
run-name: ${{ gitea.actor }} is testing the code
on: [push]

jobs:
  build:

    env:
      PY_COLORS: "1"
    runs-on: ubuntu-latest
    # strategy:
    #   fail-fast: false
    #   max-parallel: 6
    #   matrix:
    #     python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        pip install -r pip.requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # Stop the build if there are flake8 issues
        flake8 . --count --show-source --statistics --exclude=temp
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y jq
        meta_data=$(curl 'https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json')
        wget $(echo $meta_data | jq -r '.channels.Stable.downloads.chrome[0].url')
        sudo apt-get install -y ca-certificates fonts-liberation \
          libappindicator3-1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 \
          libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 \
          libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 \
          libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 \
          libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 \
          libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils
    - name: Check the console scripts interface
      run: |
        seleniumbase
        sbase
    - name: Install chromedriver
      run: |
        meta_data=$(curl 'https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json')
        seleniumbase get chromedriver $(echo $meta_data | jq -r '.channels.Stable.downloads.chrome[0].url' | awk -F"/" '{print $5}')
    - name: Make sure pytest is working
      run: |
        echo "def test_1(): pass" > nothing.py
        pytest nothing.py
    - name: Make sure nosetests is working
      run: |
        echo "def test_2(): pass" > nothing2.py
        nosetests nothing2.py
    - name: Exec test
      run: |
        pytest --browser=chrome --headless
